In [1]:
import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

In [2]:
x

In [3]:


txt = "The rain in Spain"

#Find all lower case characters alphabetically between "a" and "m":

x = re.findall("[a-m]", txt)
print(x)

['h', 'e', 'a', 'i', 'i', 'a', 'i']

In [4]:
txt = "That will be 59 dollars"

#Find all digit characters:

x = re.findall("\d", txt)
print(x)

['5', '9']

In [5]:
txt = "hello world"

#Search for a sequence that starts with "he", followed by two (any) characters, and an "o":

x = re.findall("he..o", txt)
print(x)

['hello']

In [6]:
txt = "hello world"

#Check if the string starts with 'hello':

x = re.findall("^hello", txt)
if x:
    print("Yes, the string starts with 'hello'")
else:
    print("No match")

Yes, the string starts with 'hello'

In [7]:
txt = "hello world"

#Check if the string ends with 'world':

x = re.findall("world$", txt)
if x:
    print("Yes, the string ends with 'world'")
else:
    print("No match")

Yes, the string ends with 'world'

In [8]:
txt = "The rain in Spain falls mainly in the plain!"

#Check if the string contains "ai" followed by 0 or more "x" characters:

x = re.findall("aix*", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['ai', 'ai', 'ai', 'ai']
Yes, there is at least one match!

In [9]:
txt = "The rain in Spain falls mainly in the plain!"

#Check if the string contains "ai" followed by 1 or more "x" characters:

x = re.findall("aix+", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[]
No match

In [10]:
txt = "The rain in Spain falls mainly in the plain!"

#Check if the string contains "a" followed by exactly two "l" characters:

x = re.findall("al{2}", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['all']
Yes, there is at least one match!

In [11]:

txt = "The rain in Spain falls mainly in the plain!"

#Check if the string contains either "falls" or "stays":

x = re.findall("falls|stays", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['falls']
Yes, there is at least one match!

In [12]:

txt = "The rain in Spain"

#Check if the string starts with "The":

x = re.findall("\AThe", txt)

print(x)

if x:
    print("Yes, there is a match!")
else:
    print("No match")

['The']
Yes, there is a match!

In [13]:
txt = "The rain in Spain"

#Check if "ain" is present at the beginning of a WORD:

x = re.findall(r"\bain", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[]
No match

In [14]:
txt = "The rain in Spain"

#Check if "ain" is present at the end of a WORD:

x = re.findall(r"ain\b", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['ain', 'ain']
Yes, there is at least one match!

In [15]:
txt = "The rain in Spain"

#Check if "ain" is present, but NOT at the beginning of a word:

x = re.findall(r"\Bain", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['ain', 'ain']
Yes, there is at least one match!

In [16]:

txt = "The rain in Spain"

#Check if "ain" is present, but NOT at the end of a word:

x = re.findall(r"ain\B", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[]
No match

In [17]:
txt = "The rain in Spain"

#Check if the string contains any digits (numbers from 0-9):

x = re.findall("\d", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[]
No match

In [18]:
txt = "The rain in Spain"

#Return a match at every no-digit character:

x = re.findall("\D", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['T', 'h', 'e', ' ', 'r', 'a', 'i', 'n', ' ', 'i', 'n', ' ', 'S', 'p', 'a', 'i', 'n']
Yes, there is at least one match!

In [19]:
txt = "The rain in Spain"

#Return a match at every white-space character:

x = re.findall("\s", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[' ', ' ', ' ']
Yes, there is at least one match!

In [20]:
txt = "The rain in Spain"

#Return a match at every NON white-space character:

x = re.findall("\S", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['T', 'h', 'e', 'r', 'a', 'i', 'n', 'i', 'n', 'S', 'p', 'a', 'i', 'n']
Yes, there is at least one match!

In [21]:
txt = "The rain in Spain"

#Return a match at every word character (characters from a to Z, digits from 0-9, and the underscore _ character):

x = re.findall("\w", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

['T', 'h', 'e', 'r', 'a', 'i', 'n', 'i', 'n', 'S', 'p', 'a', 'i', 'n']
Yes, there is at least one match!

In [22]:
txt = "The rain in Spain"

#Return a match at every NON word character (characters NOT between a and Z. Like "!", "?" white-space etc.):

x = re.findall("\W", txt)

print(x)

if x:
    print("Yes, there is at least one match!")
else:
    print("No match")

[' ', ' ', ' ']
Yes, there is at least one match!

In [23]:
txt = "The rain in Spain"

#Check if the string ends with "Spain":

x = re.findall("Spain\Z", txt)

print(x)

if x:
    print("Yes, there is a match!")
else:
    print("No match")

['Spain']
Yes, there is a match!

In [24]:
txt="""Regular expression is a sequence of character(s) mainly us
ed to find and replace patterns in a string or file"""


start = txt.find("Regular") + len("Regular")
end = txt.find("file")
substring = txt[start:end]
print(substring)

 expression is a sequence of character(s) mainly us
ed to find and replace patterns in a string or

In [25]:
replacement_patterns = [
(r'won\'t', 'will not'),
(r'can\'t', 'cannot'),
(r'i\'m', 'i am'),
(r'ain\'t', 'is not'),
(r'(\w+)\'ll', '\g<1> will'),
(r'(\w+)n\'t', '\g<1> not'),
(r'(\w+)\'ve', '\g<1> have'),
(r'(\w+)\'s', '\g<1> is'),
(r'(\w+)\'re', '\g<1> are'),
(r'(\w+)\'d', '\g<1> would')]

In [26]:
class RegexpReplacer :
    def __init__(self, patterns=replacement_patterns):
        self.patterns = [(re.compile(regex), repl) for (regex, repl)in patterns]
    def replace(self, text):
        s = text
        for (pattern, repl) in self.patterns:
            (s, count) = re.subn(pattern, repl, s)
        return s

In [27]:
Sentence1="We'll see how to replace words using regular expressions such doesn't, can’t and so on"
replacer = RegexpReplacer()
print(replacer.replace(Sentence1))

We will see how to replace words using regular expressions such does not, can’t and so on

In [28]:
class RepeatReplacer(object):
    def __init__(self):
        self.repeat_regexp = re.compile(r'(\w*)(\w)\2(\w*)')
        self.repl = r'\1\2\3'
    def replace(self, word):
        repl_word = self.repeat_regexp.sub(self.repl, word)
        if repl_word != word:
             return self.replace(repl_word)
        else:
             return repl_word

In [29]:
Sentence = "We likkkkkke python"
repeater = RepeatReplacer()
print(repeater.replace(Sentence))

We like python

In [30]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\omen\anaconda3\lib\site-packages (4.8.0)
Requirement already satisfied: soupsieve>=1.2 in c:\users\omen\anaconda3\lib\site-packages (from beautifulsoup4) (1.9.3)
Note: you may need to restart the kernel to use updated packages.

In [31]:
import re
from bs4 import BeautifulSoup
import requests

In [37]:
import requests
import re

data = requests.get('https://www.azolve.com/contact/contact-information.aspx')

phones = re.findall(r'[\+\(]?[1-9][0-9 .\-\(\)]{8,}[0-9]', data.text)
emails = re.findall(r'([\d\w\.]+@[\d\w\.\-]+\.\w+)', data.text)

print(phones)
print(emails)

['(55.8657822', '(41.0349577', '73.7648355', '(55.8657822', '55.8657763', '48884188282824', '41.0349577', '73.7648355', '23.7507038', '90.3933677', '(55.8657822', '(41.0349577', '73.7648355', '(23.7507038', '90.3933677', '+44 (0)141 459 0105', '+1 (914) 517 7550', '1550553099', '+44 (0)141 459 0105', '+44 (0)141 459 0105', '+44 (0)141 459 0105', '472108972810571', '106897833941558187028', '24881066-1']
['sales@azolve.com', 'sales@azolve.com', 'info@azolve.com', 'info@azolve.com', 'support@azolve.com', 'servicedesk@azolve.com', 'finance@azolve.com', 'finance@azolve.com']

In [48]:
import requests
from bs4 import BeautifulSoup

data = requests.get('https://www.worldometers.info/coronavirus/')

soup = BeautifulSoup(data.text, 'html.parser')

contentTable  = soup.find('table', { "class" : "table"}) # Use dictionary to pass key : value pair
rows  = contentTable.find_all('tr')
for row in rows:
    print(row.get_text())

#
Country,Other
TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
NewRecovered
ActiveCases
Serious,Critical
Tot Cases/1M pop
Deaths/1M pop
TotalTests
Tests/
1M pop

Population
Continent
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl




North America

9,129,340
+4,619
316,262
+232
5,935,270
+4,673
2,877,808
17,495





North America








Asia

11,089,619
+3,664
201,508
+4
9,378,721
+9,282
1,509,390
20,768





Asia








South America

8,287,914
+299
261,464
+28
7,142,208
+442
884,242
17,446





South America








Europe

5,338,812
+2,612
225,073
+20
2,883,276
+34
2,230,463
9,123





Europe








Africa

1,522,928

36,569

1,260,391

225,968
1,633





Africa








Oceania

31,563
+9
936

28,793
+2
1,834
18





Australia/Oceania










721

15

651

55
4













World
35,400,897
+11,203
1,041,827
+284
26,629,310
+14,433
7,729,760
66,487
4,542
133.7



All






1
USA
7,636,912

214,611

4,849,038

2,573,263
14,198
23,037
647
111,470,266
336,250
331,510,437
North America
431,5453


2
India
6,623,815
+1,635
102,714

5,586,703
+3,250
934,398
8,944
4,788
74
79,982,394
57,810
1,383,530,375
Asia
20913,47017


3
Brazil
4,915,289

146,375

4,263,208

505,706
8,318
23,081
687
17,900,000
84,056
212,953,890
South America
431,45512


4
Russia
1,215,001

21,358

979,143

214,500
2,300
8,325
146
47,683,832
326,711
145,950,977
Europe
1206,8343


5
Colombia
855,052

26,712

761,674

66,666
2,220
16,758
524
3,894,289
76,323
51,023,638
South America
601,91013


6
Peru
828,169

32,742

706,223

89,204
1,287
25,027
989
3,952,298
119,439
33,090,379
South America
401,0118


7
Spain
810,807

32,086

N/A
N/A
N/A
1,566
17,340
686
12,723,989
272,115
46,759,558
Europe
581,4574


8
Argentina
798,486

21,018

636,672

140,796
3,950
17,625
464
2,064,250
45,565
45,303,674
South America
572,15522


9
Mexico
761,665
+3,712
79,088
+208
550,053
+4,523
132,524
2,401
5,891
612
2,003,141
15,494
129,284,391
North America
1701,63565


10
South Africa
681,289

16,976

614,781

49,532
539
11,450
285
4,269,626
71,756
59,502,099
Africa
873,50514


11
France
619,190

32,230

97,778

489,182
1,276
9,481
493
11,469,737
175,616
65,311,522
Europe
1052,0266


12
UK
502,978

42,350

N/A
N/A
N/A
368
7,399
623
25,048,460
368,471
67,979,397
Europe
1351,6053


13
Iran
471,772

26,957

389,966

54,849
4,154
5,598
320
4,123,173
48,928
84,270,921
Asia
1793,12620


14
Chile
470,179

12,979

442,070

15,130
856
24,541
677
3,466,553
180,937
19,158,936
South America
411,4766


15
Iraq
379,141

9,399

307,482

62,260
523
9,373
232
2,349,433
58,080
40,451,877
Asia
1074,30417


16
Bangladesh
368,690

5,348

281,656

81,686

2,233
32
1,989,664
12,050
165,115,692
Asia
44830,87483


17
Saudi Arabia
336,387

4,875

321,485

10,027
955
9,624
139
6,678,019
191,055
34,953,378
Asia
1047,1705


18
Italy
325,329

35,986

231,914

57,429
303
5,383
595
11,784,105
194,977
60,438,292
Europe
1861,6795


19
Turkey
324,443

8,441

285,050

30,952
1,475
3,836
100
10,806,285
127,772
84,574,545
Asia
26110,0198


20
Philippines
322,497

5,776

273,079

43,642
1,758
2,933
53
3,873,843
35,230
109,957,856
Asia
34119,03728


21
Pakistan
314,616

6,513

298,968

9,135
513
1,417
29
3,644,762
16,419
221,988,411
Asia
70634,08461


22
Indonesia
303,498

11,151

228,453

63,894

1,107
41
3,488,141
12,718
274,274,332
Asia
90424,59679


23
Germany
301,571

9,602

261,900

30,069
373
3,596
115
16,999,253
202,724
83,854,334
Europe
2788,7335


24
Israel
268,175
+1,400
1,719

201,392
+5,763
65,064
878
29,157
187
3,703,125
402,619
9,197,590
Asia
345,3512


25
Ukraine
226,462

4,397

100,107

121,958
177
5,187
101
2,382,259
54,559
43,663,726
Europe
1939,93018


26
Canada
166,156

9,481

140,243

16,432
126
4,392
251
7,625,793
201,590
37,828,308
North America
2283,9905


27
Ecuador
141,034

11,647

120,511

8,876
354
7,963
658
453,823
25,622
17,712,036
South America
1261,52139


28
Bolivia
136,868
+299
8,101
+28
97,547
+442
31,220
71
11,684
692
307,040
26,211
11,714,131
South America
861,44638


29
Romania
135,900

5,003

108,135

22,762
598
7,077
261
2,510,209
130,717
19,203,449
Europe
1413,8388


30
Netherlands
135,892

6,454

N/A
N/A
N/A
174
7,926
376
2,449,577
142,875
17,144,850
Europe
1262,6567


31
Morocco
133,272

2,330

111,036

19,906
461
3,600
63
2,711,203
73,229
37,023,865
Africa
27815,89014


32
Belgium
130,235
+2,612
10,064
+20
19,679
+34
100,492
186
11,224
867
3,402,761
293,269
11,602,851
Europe
891,1533


33
Qatar
126,498

216

123,475

2,807
58
45,052
77
795,768
283,413
2,807,805
Asia
2212,9994


34
Panama
115,286

2,423

91,809

21,054
110
26,611
559
504,299
116,406
4,332,239
North America
381,7889


35
Dominican Republic
114,480

2,134

90,366

21,980
170
10,526
196
493,091
45,337
10,876,171
North America
955,09722


36
Kazakhstan
108,236
+59
1,725

103,277
+72
3,234
221
5,747
92
2,973,489
157,872
18,834,863
Asia
17410,9196


37
Kuwait
107,025

624

99,040

7,361
142
24,966
146
757,815
176,777
4,286,844
Asia
406,8706


38
Egypt
103,683

5,981

97,355

347
41
1,008
58
135,000
1,313
102,828,135
Africa
99217,192762


39
Oman
101,270

977

90,296

9,997
210
19,704
190
376,700
73,296
5,139,449
Asia
515,26014


40
Poland
100,074

2,630

73,003

24,441
191
2,645
70
3,447,281
91,112
37,835,645
Europe
37814,38611


41
UAE
98,801

426

88,123

10,252

9,958
43
10,132,865
1,021,320
9,921,338
Asia
10023,2901


42
Sweden
94,283

5,895

N/A
N/A
N/A
20
9,320
583
1,661,484
164,248
10,115,730
Europe
1071,7166


43
Guatemala
93,963

3,293

82,454

8,216
5
5,220
183
337,896
18,772
18,000,398
North America
1925,46653


44
Nepal
86,823

535

64,069

22,219

2,966
18
1,074,448
36,707
29,271,074
Asia
33754,71227


45
Japan
85,339

1,597

78,315

5,427
133
675
13
2,166,131
17,141
126,373,720
Asia
1,48179,13258


46
Czechia
82,446

727

44,149

37,570
245
7,695
68
1,449,352
135,274
10,714,212
Europe
13014,7387


47
Belarus
79,852

851

75,148

3,853

8,451
90
1,897,263
200,800
9,448,502
Europe
11811,1035


48
Honduras
79,629
+841
2,422
+23
29,305
+118
47,902
30
8,007
244
186,350
18,738
9,945,117
North America
1254,10653


49
Costa Rica
79,182

950

45,007

33,225
213
15,507
186
238,248
46,658
5,106,221
North America
645,37521


50
Portugal
79,151

2,005

50,207

26,939
105
7,768
197
2,647,756
259,869
10,188,821
Europe
1295,0824


51
Ethiopia
78,819

1,222

33,060

44,537
285
681
11
1,301,570
11,251
115,684,171
Africa
1,46894,66889


52
Venezuela
78,434

653

68,917

8,864
215
2,760
23
1,965,367
69,168
28,414,568
South America
36243,51414


53
Bahrain
72,662

260

67,475

4,927
64
42,337
151
1,478,163
861,271
1,716,258
Asia
246,6011


54
Nigeria
59,345

1,113

50,768

7,464
7
286
5
535,733
2,583
207,432,403
Africa
3,495186,372387


55
Uzbekistan
58,859
+247
483
+3
55,318
+37
3,058
252
1,752
14
1,377,915
41,016
33,594,251
Asia
57169,55324


56
Singapore
57,812

27

57,575

210

9,862
5
2,885,545
492,217
5,862,339
Asia
101217,1242


57
Moldova
56,579

1,366

40,955

14,258
685
14,034
339
292,588
72,576
4,031,478
Europe
712,95114


58
Switzerland
54,384

2,077

45,800

6,507
33
6,272
240
1,391,498
160,475
8,671,140
Europe
1594,1756


59
Armenia
52,496

977

44,672

6,847

17,707
330
306,965
103,540
2,964,701
Asia
563,03410


60
Algeria
52,136

1,760

36,578

13,798
23
1,183
40


44,053,891
Africa
84525,031


61
Austria
48,146

813

38,629

8,704
103
5,338
90
1,686,373
186,963
9,019,845
Europe
18711,0955


62
Kyrgyzstan
47,635
+207
1,066

43,521
+103
3,048
24
7,270
163
276,522
42,205
6,551,846
Asia
1386,14624


63
Ghana
46,829

303

46,060

466
4
1,499
10
488,427
15,636
31,238,252
Africa
667103,09764


64
Lebanon
44,482

406

19,782

24,294
161
6,525
60
889,920
130,538
6,817,317
Asia
15316,7918


65
Paraguay
44,182

929

27,203

16,050
145
6,175
130
288,502
40,321
7,155,212
South America
1627,70225


66
Palestine
41,498

330

34,698

6,470

8,087
64
433,343
84,448
5,131,507
Asia
12415,55012


67
Azerbaijan
40,691

596

38,496

1,599

4,004
59
1,137,121
111,889
10,162,960
Asia
25017,0529


68
Kenya
39,427

731

25,659

13,037

729
14
563,483
10,421
54,072,535
Africa
1,37173,97196


69
Afghanistan
39,341

1,462

32,852

5,027
93
1,005
37
111,937
2,859
39,151,119
Asia
99526,779350


70
Ireland
38,032

1,810

23,364

12,858
20
7,680
366
1,221,801
246,724
4,952,088
Europe
1302,7364


71
Libya
36,809

592

21,429

14,788

5,338
86
218,698
31,716
6,895,418
Africa
18711,64832


72
Serbia
33,901

754

31,536

1,611
21
3,884
86
1,154,457
132,270
8,728,018
Europe
25711,5768


73
Hungary
30,575

822

7,470

22,283
42
3,167
85
759,174
78,640
9,653,847
Europe
31611,74413


74
Denmark
29,680

658

22,716

6,306
33
5,119
113
4,048,223
698,263
5,797,559
Europe
1958,8111


75
El Salvador
29,450

863

24,296

4,291
38
4,534
133
405,807
62,482
6,494,778
North America
2217,52616


76
Bosnia and Herzegovina
28,354

879

21,859

5,616

8,657
268
247,897
75,685
3,275,378
Europe
1163,72613


77
Australia
27,144
+8
894

24,866

1,384
6
1,061
35
7,788,799
304,529
25,576,542
Australia/Oceania
94228,6093


78
S. Korea
24,164
+73
422
+1
21,886
+41
1,856
107
471
8
2,352,378
45,872
51,280,822
Asia
2,122121,51922


79
Tunisia
22,230

321

5,032

16,877
116
1,876
27
250,479
21,136
11,850,723
Africa
53336,91847


80
Bulgaria
21,587

844

15,014

5,729
56
3,113
122
543,076
78,315
6,934,471
Europe
3218,21613


81
Cameroon
20,924

420

19,764

740
30
783
16
149,000
5,578
26,713,033
Africa
1,27763,602179


82
Ivory Coast
19,882

120

19,449

313

749
5
166,529
6,274
26,543,565
Africa
1,335221,196159


83
Greece
19,842

409

9,989

9,444
82
1,906
39
1,349,123
129,605
10,409,506
Europe
52525,4518


84
North Macedonia
18,790

756

15,341

2,693
3
9,019
363
195,002
93,600
2,083,351
Europe
1112,75611


85
Myanmar
17,794

412

5,195

12,187

326
8
324,590
5,955
54,505,092
Asia
3,063132,294168


86
Croatia
17,659

298

15,849

1,512
25
4,309
73
326,159
79,580
4,098,517
Europe
23213,75313


87
Madagascar
16,558

232

15,486

840
13
594
8
72,572
2,604
27,870,839
Africa
1,683120,133384


88
Jordan
15,640

101

5,240

10,299
48
1,529
10
1,291,402
126,244
10,229,453
Asia
654101,2828


89
Senegal
15,094

312

12,805

1,977
7
896
19
182,186
10,809
16,855,249
Africa
1,11754,02393


90
Zambia
15,052

333

14,187

532

813
18
163,179
8,814
18,513,446
Africa
1,23055,596113


91
Norway
14,457

275

11,190

2,992
3
2,661
51
1,075,807
198,039
5,432,295
Europe
37619,7545


92
Albania
14,266

396

8,675

5,195
23
4,959
138
87,710
30,487
2,876,966
Europe
2027,26533


93
Sudan
13,653

836

6,764

6,053

310
19


44,109,014
Africa
3,23152,762


94
Slovakia
13,139

55

4,828

8,256
37
2,406
10
492,902
90,269
5,460,340
Europe
41699,27911


95
Malaysia
12,381

137

10,283

1,961
28
381
4
1,581,208
48,693
32,473,219
Asia
2,623237,03121


96
Montenegro
12,127

179

7,953

3,995
17
19,308
285
71,582
113,968
628,087
Europe
523,5099


97
Namibia
11,626

123

9,429

2,074
8
4,554
48
103,254
40,449
2,552,692
Africa
22020,75425


98
DRC
10,760

274

10,239

247

119
3


90,243,090
Africa
8,387329,354


99
Guinea
10,754

66

10,098

590
24
813
5
33,676
2,547
13,222,537
Africa
1,230200,341393


100
Finland
10,538

345

8,100

2,093
4
1,901
62
1,081,369
195,088
5,542,988
Europe
52616,0675


101
Maldives
10,530

34

9,364

1,132
12
19,393
63
149,135
274,658
542,985
Asia
5215,9704


102
French Guiana
10,029

67

9,665

297
4
33,359
223
67,481
224,460
300,637
South America
304,4874


103
Tajikistan
9,935

78

8,749

1,108

1,036
8


9,592,085
Asia
965122,975


104
Mozambique
9,196

66

5,852

3,278

292
2
144,618
4,595
31,475,668
Africa
3,423476,904218


105
Luxembourg
8,890

126

7,428

1,336
5
14,143
200
856,485
1,362,539
628,595
Europe
714,9891


106
Haiti
8,819

229

6,992

1,598

771
20
28,702
2,509
11,438,507
North America
1,29749,950399


107
Uganda
8,808

81

4,736

3,991

191
2
491,547
10,662
46,101,840
Africa
5,234569,15994


108
Gabon
8,797

54

8,067

676
3
3,929
24
180,173
80,468
2,239,052
Africa
25541,46412


109
Georgia
8,118

50

4,244

3,824

2,036
13
639,816
160,470
3,987,139
Asia
49179,7436


110
Zimbabwe
7,888

228

6,359

1,301

529
15
160,162
10,736
14,918,696
Africa
1,89165,43393


111
Mauritania
7,520

162

7,188

170
3
1,607
35
80,832
17,270
4,680,497
Africa
62228,89258


112
Jamaica
6,895

120

2,460

4,315
12
2,326
40
80,591
27,185
2,964,557
North America
43024,70537


113
Slovenia
6,498

155

4,265

2,078
26
3,126
75
236,511
113,761
2,079,013
Europe
32013,4139


114
Cabo Verde
6,360

65

5,416

879

11,407
117
76,576
137,343
557,554
Africa
888,5787


115
Cuba
5,809

122

5,145

542
1
513
11
643,701
56,840
11,324,788
North America
1,95092,82618


116
Malawi
5,786

179

4,541

1,066
4
300
9
54,351
2,823
19,254,787
Africa
3,328107,569354


117
Eswatini
5,569

111

5,127

331
11
4,787
95
32,234
27,710
1,163,283
Africa
20910,48036


118
Guadeloupe
5,528

57

2,199

3,272
24
13,815
142
55,187
137,919
400,142
North America
727,0207


119
Djibouti
5,419

61

5,349

9

5,464
62
77,743
78,393
991,704
Africa
18316,25713


120
Angola
5,402

195

2,577

2,630
16
163
6
85,213
2,573
33,121,882
Africa
6,131169,856389


121
Lithuania
5,185

94

2,495

2,596

1,912
35
799,446
294,776
2,712,045
Europe
52328,8523


122
Nicaragua
5,170

151

2,913

2,106

778
23


6,644,965
North America
1,28544,006


123
Hong Kong
5,114

105

4,861

148
10
681
14
3,311,279
440,750
7,512,834
Asia
1,46971,5512


124
Congo
5,089

89

3,887

1,113

917
16


5,552,466
Africa
1,09162,387


125
Equatorial Guinea
5,045

83

4,879

83
4
3,567
59
60,916
43,066
1,414,470
Africa
28017,04223


126
Suriname
4,941

106

4,741

94
6
8,403
180
14,638
24,895
588,000
South America
1195,54740


127
Rwanda
4,866

29

3,216

1,621

373
2
504,670
38,721
13,033,460
Africa
2,678449,43026


128
CAR
4,845

62

1,914

2,869
2
999
13
32,263
6,650
4,851,305
Africa
1,00178,247150


129
Trinidad and Tobago
4,763

81

2,843

1,839
13
3,400
58
32,354
23,099
1,400,679
North America
29417,29243


130
Bahamas
4,409

96

2,375

1,938
96
11,184
244
21,445
54,398
394,221
North America
894,10618


131
Syria
4,366

205

1,155

3,006

248
12


17,608,331
Asia
4,03385,894


132
Réunion
4,178

16

3,360

802
17
4,658
18
35,419
39,487
896,980
Africa
21556,06125


133
Aruba
4,079

30

3,532

517
12
38,163
281
32,776
306,647
106,885
North America
263,5633


134
Mayotte
3,779

42

2,964

773
2
13,768
153
13,000
47,362
274,483
Africa
736,53521


135
Somalia
3,745

99

3,010

636

234
6


16,004,765
Africa
4,274161,664


136
Estonia
3,607

67

2,749

791
2
2,719
50
220,977
166,553
1,326,770
Europe
36819,8036


137
Gambia
3,594

115

2,226

1,253

1,477
47
17,472
7,179
2,433,741
Africa
67721,163139


138
Thailand
3,590
+5
59

3,390
+2
141
1
51
0.8
749,213
10,727
69,846,049
Asia
19,4561,183,83193


139
Sri Lanka
3,402

13

3,258

131

159
0.6
289,588
13,509
21,436,802
Asia
6,3011,648,98574


140
Malta
3,270

39

2,758

473

7,401
88
263,454
596,249
441,852
Europe
13511,3302


141
Mali
3,184

131

2,479

574

156
6
56,337
2,762
20,397,311
Africa
6,406155,705362


142
Botswana
3,172

16

710

2,446
1
1,342
7
184,076
77,875
2,363,744
Africa
745147,73413


143
Guyana
3,093

87

1,920

1,086
18
3,927
110
14,815
18,812
787,547
South America
2559,05253


144
Iceland
2,921

10

2,277

634
3
8,545
29
287,010
839,648
341,822
Europe
11734,1821


145
South Sudan
2,726

50

1,290

1,386

243
4
12,044
1,073
11,227,721
Africa
4,119224,554932


146
Guinea-Bissau
2,362

39

1,549

774
5
1,193
20


1,979,796
Africa
83850,764


147
Benin
2,357

41

1,973

343

193
3
203,831
16,703
12,203,338
Africa
5,177297,64260


148
Sierra Leone
2,269

72

1,706

491

283
9


8,018,368
Africa
3,534111,366


149
Belize
2,196
+65
30
+1
1,378
+32
788
5
5,497
75
15,982
40,007
399,477
North America
18213,31625


150
Burkina Faso
2,167

59

1,419

689

103
3


21,047,594
Africa
9,713356,739


151
Uruguay
2,145

48

1,844

253
2
617
14
246,766
70,973
3,476,892
South America
1,62172,43514


152
Andorra
2,110

53

1,540

517
9
27,297
686
137,457
1,778,274
77,298
Europe
371,4581


153
Latvia
2,086

38

1,307

741
3
1,109
20
334,829
178,044
1,880,597
Europe
90249,4896


154
Yemen
2,041

591

1,320

130

68
20


29,993,034
Asia
14,69550,750


155
French Polynesia
1,964

8

1,555

401
11
6,981
28
26,355
93,679
281,333
Australia/Oceania
14335,16711


156
New Zealand
1,855
+1
25

1,790
+2
40

371
5
982,819
196,481
5,002,100
Australia/Oceania
2,697200,0845


157
Togo
1,854

48

1,392

414

223
6
95,110
11,421
8,327,944
Africa
4,492173,49988


158
Cyprus
1,824

22

1,369

433
1
1,508
18
391,475
323,626
1,209,653
Asia
66354,9843


159
Lesotho
1,683

39

926

718

784
18
19,428
9,050
2,146,677
Africa
1,27655,043110


160
Martinique
1,543

21

98

1,424
16
4,113
56
36,331
96,834
375,188
North America
24317,86610


161
Liberia
1,348

82

1,236

30

265
16


5,087,832
Africa
3,77462,047


162
Chad
1,217

86

1,075

56

74
5


16,544,254
Africa
13,594192,375


163
Niger
1,200

69

1,115

16

49
3
26,062
1,067
24,423,548
Africa
20,353353,964937


164
Vietnam
1,096

35

1,020

41

11
0.4
1,009,145
10,343
97,566,509
Asia
89,0212,787,61597


165
Sao Tome and Principe
913

15

887

11

4,146
68
5,109
23,202
220,201
Africa
24114,68043


166
San Marino
732

42

680

10
3
21,561
1,237
7,755
228,424
33,950
Europe
468084


167
Diamond Princess
712

13

651

48
4









168
Turks and Caicos
695

6

656

33
4
17,888
154
3,464
89,159
38,852
North America
566,47511


169
Sint Maarten
679
+1
22

572

85
6
15,790
512
3,803
88,438
43,002
North America
631,95511


170
Channel Islands
678

48

600

30
2
3,890
275
123,884
710,833
174,280
Europe
2573,6311


171
Papua New Guinea
540

7

527

6

60
0.8
25,955
2,887
8,990,371
Australia/Oceania
16,6491,284,339346


172
Taiwan
517

7

484

26

22
0.3
94,734
3,976
23,828,127
Asia
46,0893,404,018252


173
Burundi
513

1

472

40

43
0.08
37,522
3,132
11,979,552
Africa
23,35211,979,552319


174
Tanzania
509

21

183

305
7
8
0.3


60,161,754
Africa
118,1962,864,845


175
Comoros
487

7

466

14

557
8


874,319
Africa
1,795124,903


176
Faeroe Islands
474



435

39

9,691

133,735
2,734,196
48,912
Europe
1030


177
Curaçao
452

1

231

220
2
2,752
6
8,045
48,975
164,269
North America
363164,26920


178
Gibraltar
432



360

72

12,824

49,040
1,455,711
33,688
Europe
781


179
Saint Martin
412

8

309

95
11
10,609
206
5,170
133,127
38,835
North America
944,8548


180
Eritrea
398



358

40

112



3,559,089
Africa
8,942


181
Mauritius
385

10

357

18

303
8
246,326
193,603
1,272,324
Africa
3,305127,2325


182
Isle of Man
342

24

315

3

4,016
282
13,257
155,688
85,151
Europe
2493,5486


183
Mongolia
314
+1


307

7
1
95

73,641
22,371
3,291,861
Asia
10,48445


184
Bhutan
298
+15


237
+7
61

385

142,510
184,166
773,812
Asia
2,5975


185
Cambodia
280
+2


275

5

17

144,119
8,589
16,778,683
Asia
59,924116


186
Monaco
222

2

189

31
1
5,647
51
51,953
1,321,455
39,315
Europe
17719,6581


187
Cayman Islands
213

1

209

3

3,231
15
39,814
603,956
65,922
North America
30965,9222


188
Barbados
199

7

182

10

692
24
24,628
85,672
287,468
North America
1,44541,06712


189
Bermuda
181

9

169

3

2,909
145
66,664
1,071,476
62,217
North America
3446,9131


190
Brunei
146

3

142

1

333
7
58,914
134,333
438,568
Asia
3,004146,1897


191
Seychelles
146



143

3

1,482

5,200
52,789
98,506
Africa
67519


192
Liechtenstein
126

1

116

9

3,302
26
900
23,587
38,157
Europe
30338,15742


193
Caribbean Netherlands
124

1

46

77

4,717
38
2,575
97,961
26,286
North America
21226,28610


194
Antigua and Barbuda
107

3

96

8

1,090
31
2,878
29,325
98,140
North America
91732,71334


195
British Virgin Islands
71

1

66

4
2
2,344
33
4,841
159,853
30,284
North America
42730,2846


196
St. Vincent Grenadines
64



64

0

576

5,360
48,274
111,033
North America
1,73521


197
St. Barth
62



37

25

6,272

2,668
269,904
9,885
North America
1594


198
Macao
46



46

0

71

4,238
6,504
651,620
Asia
14,166154


199
Fiji
32

2

28

2
1
36
2
10,385
11,563
898,141
Australia/Oceania
28,067449,07186


200
Dominica
31



24

7

430

2,612
36,261
72,033
North America
2,32428


201